### ISSUE TITLE
Include rclone

### ISSUE THREAD

**Issue by rgarrigue** [Lobaro/restic-backup-docker#14]
Hi

Would you mind adding rclone in this container ? I'ld be interested so I can backup to a FTP repository.

Best regards,

**Comment by Niondir** [comment]
Hello @rgarrigue,
I would prefer to keep the restic container clean. Most cases can be solved by restic directly or linking to the root system.
Adding rclone might bring a lot of complexity to the container configuration.

Isn't it possible to configure restic to backup directly to FTP servers?

What I did before was mounting the FTP repo on the root system and link the mounted folder into the backup container.

**Comment by rgarrigue** [comment]
Hi 

SFTP is available but not FTP, and Online.net where I rent my server provide a free FTP space for backup, hence my question. but curlftpfs to mount ftp as a folder seems to be a decent approach, I guess I'll check this one.

Thanks for the advice
