### ISSUE TITLE
Can u add the environment variables to support B2?

### ISSUE THREAD

**Issue by jwillmer** [lobaro/restic-backup-docker#15]
[Backblaze B2 Cloud Storage](https://www.backblaze.com/b2/cloud-storage.html)

**Comment by jwillmer** [comment]
If I compar your dockerfile with the one from [instrumentisto](https://github.com/instrumentisto/restic-docker-image/blob/master/Dockerfile) I get the feeling that it might be already possible?

**Comment by Niondir** [comment]
Oh well I was not looking for it but you might be lucky with `RESTIC_JOB_ARGS` :)

**Comment by Niondir** [comment]
Seems to be solved.
