### ISSUE TITLE
"ssh": executable file not found in $PATH

### ISSUE THREAD

**Issue by mrclschstr** [lobaro/restic-backup-docker#27]
I try to use the docker image tagged as `latest` for backing up to SFTP. It seems like there is an issue with the $PATH variable. My output looks the following.

> Starting container ...
> Restic repository 'sftp:username@server:/some/path' does not exists. Running restic init.
> Setup backup cron job with cron expression BACKUP_CRON: */5 * * * *
> Container started.
> create backend at sftp:username@server:/some/path failed: cmd.Start: exec: "ssh": executable file not found in $PATH

The images `v1.0` and `v1.1` are working fine. Am I doing something wrong?

**Comment by Niondir** [comment]
Thanks for reporting.
Looks like ssh got lost. Maybe some change in the busybox base image? I would need to take a deeper look into this. 

PR are welcome.

**Comment by Niondir** [comment]
We could at least pin the version of the base image to avoid such issued in future.

**Comment by Niondir** [comment]
The official image is adding ssh-client to the alpine image:
`RUN apk add --update --no-cache ca-certificates fuse openssh-client`

See also: #23

I guess we should kick out busybox and rely on alpine

**Comment by wuast94** [comment]
i got down to version 1.1 now to get ssh backups running. would be nice to see this fixed in next release :)

**Comment by Niondir** [comment]
With the "latest" release I can go into my container and execute "ssh" without issues. I assume it's fixed.
