### ISSUE TITLE
Environment variable HOSTNAME not used

### ISSUE THREAD

**Issue by vfauth** [lobaro/restic-backup-docker#45]
The possibility to use the environment variable HOSTNAME listed [there](https://github.com/lobaro/restic-backup-docker#set-the-hostname) does not work, the only way it to use the docker --hostname option.

**Comment by Niondir** [comment]
Thanks for pointing this out. We should correct the docs. One way to set the host name is probably enough :)

**Comment by vfauth** [comment]
But I don't use compose.

**Comment by Niondir** [comment]
Okay, good to know. I guess I misinterpreted the docker docs. They overwrite the HOSTNAME env so when we set it it's not used.
