### ISSUE TITLE
Permission denied on OpenShift

### ISSUE THREAD

**Issue by daquinoaldo** [lobaro/restic-backup-docker#47]
Hi,
I receive a permission denied error when running on OpenShift.

It occurs when the init script tries to perform `mkdir` in a subpath of `/mnt` and again when it tries to setup the cron job.

**This is a known bug, with an official fix.** OpenShift Container Platform runs containers using an arbitrarily assigned user ID instead of privileged user (root). Since the user inside the container is not root, it hasn't the permissions to perform some operations you do in the bootstrap script, like creating directory inside `/mnt` or setup the cron job (that btw I really enjoy, thanks!).

**The bug affects all the OpenShift users.**  
I'll open a PR, I hope you will consider merging the fix, to allow your image to be run on OpenShift.

**Comment by Niondir** [comment]
Thanks a lot for the contribution.

**Comment by daquinoaldo** [comment]
Thank you for your work!
