### ISSUE TITLE
Backup not aborting correctly after error

### ISSUE THREAD

**Issue by mrclschstr** [lobaro/restic-backup-docker#52]
Hi all,

my backup failed today but the script didn't abort correctly. I think it's better to use `exit 1` instead of the `kill` in the following line:

https://github.com/lobaro/restic-backup-docker/blob/ec42bdd04c68553101c6012018592979cdc4abf3/backup.sh#L35

The `kill` command is more useful for killing processes than for quitting scripts.

What do you think?

**EDIT:** By the way... with `kill 1` you are trying to killing the process with pid 1 😉

**Comment by Niondir** [comment]
Looks like an bug. I agree that it should be `exit 1`

**Comment by Niondir** [comment]
I just changed it.
