### ISSUE TITLE
Pulling the docker with unraid doesn't enable rclone

### ISSUE THREAD

**Issue by hrv231** [lobaro/restic-backup-docker#62]
I was able to follow your guide from: https://github.com/lobaro/restic-backup-docker

Since I'm using unraid, i didn't have to run ./build.sh  or ./run.sh

I added some volumes from my unraid shares to your docker.
After following the "Backup via rclone" part, I see that rclone is not in the $PATH.

Below is my unraid template for your docker:
![unraid template config](https://user-images.githubusercontent.com/41212308/115158403-cfd41300-a042-11eb-8a50-ca66788bd731.jpg)

Below is the problem with rclone:
![restic docker rclone not found](https://user-images.githubusercontent.com/41212308/115158411-d82c4e00-a042-11eb-9a2c-79550312fa38.jpg)

Let me know if you need more information on this, ready to help!

I want this docker to function with rclone at full, for my backups :-)

**Comment by Niondir** [comment]
Thanks for the report.
Feel free to make a PR and add the rclone to the `$PATH` var.

**Comment by vbifonixor** [comment]
Why'd you have this issue closed? It seems that it wasn't resolved, only reported

**Comment by vbifonixor** [comment]
In fact, I'm trying to set up this container in my docker-compose config (without having to run commands manually) and I get the same error - rclone is not in the `$PATH`
