### ISSUE TITLE
Update to restic 0.12.1

### ISSUE THREAD

**Issue by huzvar** [lobaro/restic-backup-docker#68]
- Pls upgrade restic version.
- Pls tagged version. Latest is not sufficient.

**Comment by niondir** [comment]
Since updating restic is pretty easy and I'm not following any regular release cycle, I suggest to fork the repo and build with your required restic version.

If someone like to help with maintaining this repo feel free to contact me.

**Comment by Brakker1328** [comment]
Update the restic container with the following command in Terminal/Powershell connecting over ssh:

    $ docker exec -ti resticcontainer restic self-update

**Comment by vfauth** [comment]
> Since updating restic is pretty easy and I'm not following any regular release cycle, I suggest to fork the repo and build with your required restic version.
> 
> If someone like to help with maintaining this repo feel free to contact me.

Hey @niondir! First, thank you for this super useful image :)

I have been "maintaining" (meaning adding new versions as soon as they are released, nothing more) in [this fork](https://github.com/vfauth/restic-backup-docker/tree/restic-0.12.0), and I could help with this repo maintenance if you want.

**Comment by niondir** [comment]
@vfauth I'm pretty bad at following the public repos besides the daily work. Help with Maintenance is very welcome.

If you are still interested I would add you as maintainer. Just give me a shot notice.

Sorry for the very late reply.

**Comment by vfauth** [comment]
@niondir Yes, I would still be interested in helping maintaining this repo.

**Comment by niondir** [comment]
Great, I added you as maintainer.

**Comment by niondir** [comment]
I updated to the latest. mailx in alpine made some issues and is now called "mail". Maybe someone who uses the feature can test it. Automated tests are still an open issue.
