### ISSUE TITLE
Add WOL support in hooks

### ISSUE THREAD

**Issue by snyssen** [lobaro/restic-backup-docker#74]
I would like to be able to wake a local server in the pre-backup hook and shut it down once the backup is done using the post-backup hook. The only thing I need for this to work is some form of wake-on-lan client, such as [Awake](https://pkgs.alpinelinux.org/package/edge/community/x86/awake). I thus propose the following modification to the [Dockerfile](https://github.com/lobaro/restic-backup-docker/blob/master/Dockerfile) (change is on [line number 9](https://github.com/lobaro/restic-backup-docker/blob/master/Dockerfile#L9)):

```diff
- RUN apk add --update --no-cache heirloom-mailx fuse curl
+ RUN apk add --update --no-cache heirloom-mailx fuse curl awake
```

Would this change be okay? I can open a PR if you would like.

**Comment by niondir** [comment]
I would recommend to just build your own container based on this one and add your dependency. It's does not feel right to add bunch of dependencies for any possible use-case.

As a workaround:
You could even install awake inside the post-backup hook if it does not exists.
