### ISSUE TITLE
Disable CRON

### ISSUE THREAD

**Issue by ghzgod** [lobaro/restic-backup-docker#75]
Is there any option to disable cron?  I want to manage this via scripts to support multiple backend backups.  So having a default cron will not work with my use case.

**Comment by niondir** [comment]
For managing restic via script it might be enough to use restic either on the host or use the official restic container directly with `docker exec`

The whole point of this container is automatic backup scheduling. You could set an invalid corn that will never trigger - I assume there is no check against that :)
