### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by jounathaen** [lobaro/restic-backup-docker#77]
Hi,
This is a very nice Dockerfile. The only caveat is, that the last release is now 1.5 years ago, and cool new features have been added. A new release would be great.
Cheers and regards!

Releated: #68 #59

**Comment by niondir** [comment]
As stated in the other Issues, I appreciate any PR that pushes versions and improves the build e.g. with GitHub actions.

Maybe I can find some time to tackle it my self, but can't promise too much.

Closing this one as duplicate.
