### ISSUE TITLE
Upgrade image to 0.7.x

### ISSUE THREAD

**Issue by scottbroadway** [Lobaro/restic-backup-docker#8]
Upgrade the latest Restic build in order to support Backblaze B2.

**Comment by Niondir** [comment]
Thank for reporting. We should also mention the restic version in the readme and find a way to create reproducible builds instead of pulling the latest restic from github.

Pull requests are very welcome. I will take care as soon as I find some time.

**Comment by djmaze** [comment]
@scottbroadway You might want to have a look at [my alternative image](https://github.com/djmaze/resticker) which contains the latest 0.7.3 release.

**Comment by Niondir** [comment]
We now have `ENV RESTIC_VERSION=0.8.1`.
